alias x='xclip -selection clipboard'
alias ls='eza -a --group-directories-first --icons'
alias lt='eza -lh --icons --sort=size --total-size --group-directories-first --reverse'
alias ll='eza -lh --icons --sort=size --group-directories-first'
alias hg='history | grep '
alias dd='docker compose down'
alias du='docker compose up -d'
